# Generated by Django 4.2.1 on 2023-05-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='comment',
            new_name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default='default text for entries created before migration', max_length=300),
        ),
    ]
